00 Components and Props Vite Updates
AdaGold/flasky-front-end pull request #6
Opened 2024-05-02 05:18 UTC by mikellewade

2024-05-07 18:01 UTC, anselrognlie requested changes
LGTM other than a minor style tweak, and some possible instructor-focused comments.

2024-05-08 21:47 UTC, mikellewade commented on src/components/Dog.jsx
> +      <li>
Gotcha, I'll add a classname of `Dog` to it.

2024-05-08 21:49 UTC, mikellewade commented on src/App.jsx
> +    { id: 3, name: 'spot', age: '10', breed: 'golden doodle', chip: '' },
Haha, I'll add some in.

2024-05-08 21:51 UTC, anselrognlie commented on src/App.jsx
> +    { id: 3, name: 'spot', age: '10', breed: 'golden doodle', chip: '' },
It's really not a big deal, but since there are other changes that also need to affect later branches, might as well? 😁

2024-05-08 22:37 UTC, mikellewade commented on src/components/DogList.jsx
> +      })
I'm sorry, could you clarify what you mean here some? I think I'm confused on the duplicated proptypes and inner and outer proptype part.

2024-05-08 22:47 UTC, mikellewade commented on src/components/DogList.jsx
> +    const getDogListJSX = (dogs) => {
Got it, will make sure to put that in there.

2024-05-08 22:50 UTC, anselrognlie commented on src/components/DogList.jsx
> +      })
Sure. In this case, Dog uses prop types like
```js
{
    id: PropTypes.number.isRequired,
    name: PropTypes.string.isRequired,
    age: PropTypes.string.isRequired,
    breed: PropTypes.string.isRequired,
    chip: PropTypes.string.isRequired,
}
```
and that's also the inner type (passed to `shape`).

So a common thing to see is to define that shared bit as a value (maybe `DogType`) in a separate file, and then have both Dog and DogList import it for their prop types.

Some authors refer to this as the [Centralized PropTypes pattern](https://www.bram.us/2017/12/03/react-pattern-centralized-proptypes/)

2024-05-08 22:52 UTC, mikellewade commented on src/components/DogList.jsx
> +      })
OH! Okay, yes I can add a comment about that!

2024-05-10 16:29 UTC, anselrognlie requested changes
Question about the style and structure of DogList

2024-05-10 16:29 UTC, anselrognlie commented on src/components/DogList.jsx
> +    return <ul className="dogs__list">{getDogListJSX(props.dogs)}</ul>;
Let's settle on one style of class name. In the previous branch it was `dogList`, but here it's `dogs__list`. Personally, I'm not a big fan of BEM-style classes, so would prefer `dogList`, but as long as we're consistent I'd be happy.

2024-05-10 16:29 UTC, anselrognlie commented on src/components/DogList.jsx
> +    return <ul className="dogs__list">{getDogListJSX(props.dogs)}</ul>;
Was the removal of `<h2> Dog List </h2>` intentional? We still have the header styling. If the heading was intended to be removed, we should also remove the style rule. If we keep the heading, then my feedback on where to stick the class name applies here as well. It should be on the outer element (we'd need to bring back the div to group the heading and list).

2024-05-10 20:07 UTC, anselrognlie approved these changes
LGTM. Could just use one more style rule.

2024-05-10 20:07 UTC, anselrognlie commented on src/components/DogList.css
> +
This could also use
```suggestion

.dogList>ul {
    padding: 0;
}

```

2024-07-10 16:33 UTC, closed without merging